### PR TITLE
Various fixes and suggestions

### PR DESCRIPTION
**Pull request by Yoann-Le-Borgne**
Hi!

While compiling the doc I encountered various problems and warnings/errors.

The first one is related to the mkdocs version used to compile the documentation. It has seen some significant updates, notably in the default templates provided (see https://github.com/mkdocs/mkdocs/releases/tag/1.6.0). I suggest using the latest version without major changes, 1.5.3. (commit 62c8eb0)

Commit 44dd9cb and ffe54f2 are fixing warnings that could be seen during compilation.

Commit 097f9c8 might be controversial for your operation as it replaces any reference to https://faustdoc.grame.fr in the markdown files for a relative link. I couldn't get any http 404 errors when locally serving it and browsing in various sections and sub-menus for quite some time but I can't guarantee it 100% as I thought it was overkill to do a before/after automated test.

Feel free to cherry-pick anything that might be of interest :)

Regards,
Yoann

### CODE REVIEW

**Comment by sletz** [comment]
Wonderful, thanks for all those fixes, regenerated and deployed.

**Comment by sletz** [comment]
@Yoann-Le-Borgne BTW https://faustlibraries.grame.fr and https://faust.grame.fr now fail to build properly with mkdocs, version 1.5.3. 
Do you have automatic tools to fix links issues ?

**Comment by Yoann-Le-Borgne** [comment]
> @Yoann-Le-Borgne BTW https://faustlibraries.grame.fr and https://faust.grame.fr now fail to build properly with mkdocs, version 1.5.3. Do you have automatic tools to fix links issues ?

I don't. The only thing that I had to change was jquery version in the base.html file for faustdocs to correctly be generated. I will have a look at both those repositories to see if anything is different.

FYI, the ./docs folder in this repository can now safely be removed as it will be correctly regenerated by mkdocs. This means that starting with mkdocs 1.5.0 you can automatically deploy to GH Pages with mkdocs (see https://www.mkdocs.org/user-guide/deploying-your-docs/)

**Comment by Yoann-Le-Borgne** [comment]
https://github.com/grame-cncm/faustlibraries/pull/197

**Comment by Yoann-Le-Borgne** [comment]
https://github.com/grame-cncm/faustwebsite/pull/20

**Pull request merged**
